Added nav bar to application view layout
tofuandeve/betsy pull request #2
Opened 2019-10-23 22:10 UTC by tofuandeve

Created a nav bar for see all merchants, login, logout buttons

2019-10-23 22:13 UTC, emaust reviewed
Change href to link_to

2019-10-23 22:15 UTC, michaela260 approved these changes

2019-10-23 22:15 UTC, mdove92 requested changes
Great work! Change the hrefs to link_tos

2019-10-23 22:15 UTC, mdove92 commented on app/views/layouts/application.html.erb
> +              <a class="nav-link" href="/products"> All Merchants</a>
```suggestion
              <a class="nav-link" href="/"> All Merchants</a>
```

2019-10-23 22:15 UTC, mdove92 commented on app/views/layouts/application.html.erb
> +        <a class="navbar-brand" href="/">Bandit</a>
should be link_to

2019-10-23 22:15 UTC, mdove92 commented on app/views/layouts/application.html.erb
> +            <li class="nav-item"><a class="nav-link" href="/">Login</a></li>
make link_to

2019-10-23 22:15 UTC, mdove92 commented on app/views/layouts/application.html.erb
> +            <li class="nav-item"><a class="nav-link" href="/">Logout</a></li>
make link_to

2019-10-23 22:54 UTC, emaust requested changes

2019-10-23 22:54 UTC, emaust commented on app/views/layouts/application.html.erb
> +
starting body tag missing

2019-10-23 22:54 UTC, emaust commented on config/routes.rb
> +  root to: 'homepages#index'
this should be homepage#index (remove s)

2019-10-24 00:16 UTC, mdove92 approved these changes

2019-10-24 03:31 UTC, tofuandeve commented on config/routes.rb
> +  root to: 'homepages#index'
@emaust Homepage is a controller, shouldn't it always be plural in the route to action?

2019-10-24 04:09 UTC, tofuandeve commented on app/views/layouts/application.html.erb
> +
@emaust it's on line 46

2019-10-24 04:16 UTC, tofuandeve commented on app/views/layouts/application.html.erb
> +
it's on line 46

2019-10-24 04:16 UTC, tofuandeve commented on config/routes.rb
> +  root to: 'homepages#index'
homepage is a controller, shouldn't it always be plural for route to controller action?

2019-10-24 04:25 UTC, emaust approved these changes

2019-10-24 04:31 UTC, merged